/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#00458e",
        "on-surface": "#191c22",
        "secondary-container": "#69affe",
        "surface-dim": "#d8d9e2",
        "surface-bright": "#f9f9ff",
        "surface-container-low": "#f2f3fc",
        "surface-container-high": "#e6e8f1",
        "primary-container": "#0066cc",
        "accent-error": "#EF4444",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#a0c9ff",
        "error-container": "#ffdad6",
        "secondary-fixed": "#d2e4ff",
        "surface-variant": "#e1e2eb",
        "primary-fixed": "#d7e3ff",
        "outline": "#727784",
        "on-primary-container": "#dfe8ff",
        "inverse-on-surface": "#eff0f9",
        "on-tertiary-container": "#ffe3d6",
        "tertiary": "#883700",
        "inverse-primary": "#aac7ff",
        "tertiary-fixed": "#ffdbcb",
        "background": "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#00497f",
        "surface-container": "#ecedf6",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-bg": "#F8FAFC",
        "on-secondary-fixed": "#001c37",
        "text-muted": "#64748B",
        "text-main": "#0F172A",
        "tertiary-fixed-dim": "#ffb692",
        "inverse-surface": "#2e3037",
        "on-background": "#191c22",
        "on-secondary-container": "#004173",
        "surface-container-highest": "#e1e2eb",
        "outline-variant": "#c1c6d5",
        "on-error": "#ffffff",
        "secondary": "#0061a6",
        "on-surface-variant": "#414753",
        "tertiary-container": "#af4900",
        "on-tertiary-fixed-variant": "#793000",
        "primary": "#004e9f",
        "surface-tint": "#005cba",
        "primary-fixed-dim": "#aac7ff",
        "on-tertiary-fixed": "#341100",
        "surface": "#f9f9ff",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#001b3e"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "80px",
        "unit": "8px",
        "gutter": "24px",
        "margin-mobile": "20px",
        "container-max": "1280px"
      },
      fontFamily: {
        "headline-lg": ["Manrope", "sans-serif"],
        "label-md": ["Manrope", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
